# -*- coding: utf-8 -*-
"""Prime_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIUTAdh_bJvq4iIZiRMZWlXhTOVGEYqV
"""

number=int(input("enter a number"))
def is_prime(number):
    if number<=1:
      return False
    for i in range(2,number):
      if number%i==0:
        return False
    return True
if is_prime(number):
  print(number,"is a prime number")
else:
  print(number,"is not a prime number")

